name: Test_and_build_artifacts_on_release

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build_apk_aab:
    if: startsWith(github.head_ref, 'release/') == true
    name: Build debug artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Build debug APK after test
        run: |
          ./gradlew test
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk